name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup apt
        run: sudo apt update && sudo apt install

      - name: Setup Python
        run: sudo apt install python3.8

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run test
        run: pytest test.py

  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: cbe32b0a-cb80-4fd5-86ff-d6cdb4003942
          heroku_app_name: "my-ghibli-api" #Must be unique in Heroku
          heroku_email: "arnaud.fontaine@edu.devinci.fr"
